modLoader="javafml"
loaderVersion="[1,)"
license="LGPL-3.0"
issueTrackerURL="https://github.com/AnAwesomGuy/elytra-enchants/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://modrinth.com/mod/chais-elytra-enchants"
logoFile="assets/${mod_id}/icon.png"
credits="AnAwesomGuy"
authors="Chai"
description="Adds two new treasure enchantments for the elytra, skipping and launch!"

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.21,)"
ordering="NONE"
side="BOTH"